# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jomo Supply Company
email: info@jomo-supply.com
description: > # this means to ignore newlines until "baseurl:"
  This is the official website of Jomo Supply Co. A Start-Up from Cologne, Germany trying to supply the world with their design goods such as beanies and ipad cases.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jomosupply

# Build settings
markdown: kramdown

theme: jekyll-theme-cayman
